name: Tests

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libraries
      run: |
        python -m pip install matplotlib
        python -m pip install pytest
    - name: Test with pytest
      run: |
        pytest
